// Single root-level ESLint flat config covering the whole pnpm workspace.
// Flat config (ESLint 9+) replaces the old .eslintrc — one file, explicit `files`
// globs per section instead of per-package config files cascading down folders.
import js from "@eslint/js";
import tseslint from "typescript-eslint";
import react from "eslint-plugin-react";
import reactHooks from "eslint-plugin-react-hooks";
import globals from "globals";
import eslintConfigPrettier from "eslint-config-prettier";

export default tseslint.config(
  {
    // Skip build output and generated code (lib/api-client-react + lib/api-zod
    // are regenerated by `orval` from openapi.yaml — never hand-edited, so
    // linting them would just flag issues we can't/shouldn't fix by hand).
    ignores: [
      "**/dist/**",
      "**/node_modules/**",
      "**/*.generated.*",
      "**/.generated/**",
      "lib/api-client-react/src/generated/**",
      "lib/api-zod/src/generated/**",
      // shadcn/ui vendors these by copying boilerplate source into the repo
      // (not hand-written, not generated by our own codegen) — same reasoning
      // as the generated folders above: nothing to gain from linting it.
      "**/components/ui/**",
      // Replit/Claude Code platform state (installed skills, caches) — not
      // part of this project's own source.
      ".local/**",
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    // Default to Node globals (process, console, __dirname, ...). Most non-React
    // files in this repo — configs, build scripts, the backend, shared libs —
    // run under Node, so this is the sane base; the browser override below
    // only applies to actual frontend src code.
    languageOptions: {
      globals: globals.node,
    },
    rules: {
      // 底線開頭的參數（_next、_res）代表「這個位置的參數刻意不用」——例如 Express
      // 的錯誤處理 middleware 必須是 4 參數簽章 (err, req, res, next)，Express 靠
      // 參數數量認出它是錯誤處理器，就算用不到 next 也不能拿掉。這是社群通用慣例，
      // 讓規則放行底線開頭的參數，而不是逐處寫 eslint-disable。
      "@typescript-eslint/no-unused-vars": ["error", { argsIgnorePattern: "^_" }],
      // no-namespace 預設連 `declare namespace` 都禁止，但「declare global +
      // namespace Express」是幫第三方套件擴充型別（module augmentation）的標準寫法
      // （見 api-server 的 mockAuth.ts 幫 Request 加 userId）。allowDeclarations
      // 只放行這種純型別宣告，真正的 runtime namespace 依然會報錯。
      "@typescript-eslint/no-namespace": ["error", { allowDeclarations: true }],
    },
  },
  {
    // Frontend packages: React components run in the browser, not Node —
    // they see `window`/`document`, not `process`/`__dirname`.
    files: [
      "artifacts/volleyball-tactics/src/**/*.{ts,tsx}",
      "artifacts/mockup-sandbox/src/**/*.{ts,tsx}",
    ],
    plugins: { react, "react-hooks": reactHooks },
    languageOptions: {
      globals: globals.browser,
    },
    // Pinned explicitly (matches the exact 19.1.0 in pnpm-workspace.yaml's
    // catalog) instead of "detect" — auto-detection crashes under ESLint 10's
    // flat-config context in this eslint-plugin-react version.
    settings: { react: { version: "19.1.0" } },
    rules: {
      ...react.configs.recommended.rules,
      // eslint-plugin-react-hooks v7's "recommended" preset bundles a much
      // bigger set of React Compiler-readiness rules (purity, immutability,
      // refs, etc.) on top of the two classic ones. Those are tuned for
      // compiler migration, not general bug-catching, and produce a lot of
      // noise on existing/vendored code — so we only take the two rules
      // that actually catch real hook bugs.
      "react-hooks/rules-of-hooks": "error",
      "react-hooks/exhaustive-deps": "warn",
      // Modern JSX transform (Vite/React 19) doesn't need React in scope.
      "react/react-in-jsx-scope": "off",
      // We use TypeScript to validate prop shapes instead of prop-types.
      "react/prop-types": "off",
    },
  },
  {
    // issue #154 PR C：把戰術白板的「單向依賴」焊進 CI。白板 store 是站位真相的「消費者」，
    // 一旦它 import 了輪轉表/計分表 store，就有能力反向寫回——那正是 #154 一系列 bug 的病根。
    // 擷取一律在 UI 邊界以「值」傳入（captureFromRotation → startSession），store 本身永遠不碰
    // 那兩個 store。依賴方向＝import 方向，用 lint 規則檢查比寫在註解裡可靠（PR 一改就會紅）。
    files: ["artifacts/volleyball-tactics/src/hooks/useTacticsBoard.ts"],
    rules: {
      "no-restricted-imports": [
        "error",
        {
          patterns: [
            {
              group: ["**/useRotationTable", "**/useScoreSheet"],
              message:
                "戰術白板必須維持單向：不得 import 輪轉表/計分表 store（會有能力反向寫回，正是 #154 病根）。擷取請在 UI 層用 captureFromRotation 以值傳入 startSession。",
            },
          ],
        },
      ],
    },
  },
  // Must be last: turns off any ESLint rule that would conflict with Prettier's
  // formatting (Prettier handles style, ESLint handles correctness).
  eslintConfigPrettier,
);
