// Single root-level ESLint flat config covering the whole pnpm workspace.
// Flat config (ESLint 9+) replaces the old .eslintrc — one file, explicit `files`
// globs per section instead of per-package config files cascading down folders.
import js from "@eslint/js";
import tseslint from "typescript-eslint";
import react from "eslint-plugin-react";
import reactHooks from "eslint-plugin-react-hooks";
import globals from "globals";
import eslintConfigPrettier from "eslint-config-prettier";

export default tseslint.config(
  {
    // Skip build output and generated code (lib/api-client-react + lib/api-zod
    // are regenerated by `orval` from openapi.yaml — never hand-edited, so
    // linting them would just flag issues we can't/shouldn't fix by hand).
    ignores: [
      "**/dist/**",
      "**/node_modules/**",
      "**/*.generated.*",
      "**/.generated/**",
      "lib/api-client-react/src/generated/**",
      "lib/api-zod/src/generated/**",
      // shadcn/ui vendors these by copying boilerplate source into the repo
      // (not hand-written, not generated by our own codegen) — same reasoning
      // as the generated folders above: nothing to gain from linting it.
      "**/components/ui/**",
      // Replit/Claude Code platform state (installed skills, caches) — not
      // part of this project's own source.
      ".local/**",
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    // Default to Node globals (process, console, __dirname, ...). Most non-React
    // files in this repo — configs, build scripts, the backend, shared libs —
    // run under Node, so this is the sane base; the browser override below
    // only applies to actual frontend src code.
    languageOptions: {
      globals: globals.node,
    },
  },
  {
    // Frontend packages: React components run in the browser, not Node —
    // they see `window`/`document`, not `process`/`__dirname`.
    files: [
      "artifacts/volleyball-tactics/src/**/*.{ts,tsx}",
      "artifacts/mockup-sandbox/src/**/*.{ts,tsx}",
    ],
    plugins: { react, "react-hooks": reactHooks },
    languageOptions: {
      globals: globals.browser,
    },
    // Pinned explicitly (matches the exact 19.1.0 in pnpm-workspace.yaml's
    // catalog) instead of "detect" — auto-detection crashes under ESLint 10's
    // flat-config context in this eslint-plugin-react version.
    settings: { react: { version: "19.1.0" } },
    rules: {
      ...react.configs.recommended.rules,
      // eslint-plugin-react-hooks v7's "recommended" preset bundles a much
      // bigger set of React Compiler-readiness rules (purity, immutability,
      // refs, etc.) on top of the two classic ones. Those are tuned for
      // compiler migration, not general bug-catching, and produce a lot of
      // noise on existing/vendored code — so we only take the two rules
      // that actually catch real hook bugs.
      "react-hooks/rules-of-hooks": "error",
      "react-hooks/exhaustive-deps": "warn",
      // Modern JSX transform (Vite/React 19) doesn't need React in scope.
      "react/react-in-jsx-scope": "off",
      // We use TypeScript to validate prop shapes instead of prop-types.
      "react/prop-types": "off",
    },
  },
  // Must be last: turns off any ESLint rule that would conflict with Prettier's
  // formatting (Prettier handles style, ESLint handles correctness).
  eslintConfigPrettier,
);
